Repository Kostiantynnn/Test, pull requests merged in 2022-11, with the labels that each got.

#1 QA-commit
  Test
Labels: test_label

#3 Test 4
  Test
Labels: test_label

#4 test-5
  Test
Labels: test_label

#15 MT-0003
  Test
Labels: sprint1, env/qa

#16 MT-0004
  Test
Labels: sprint1, env/qa

#19 MT-0005
  Test
Labels: sprint1, env/qa

#22 MT-0007
  Test
Labels: sprint1, env/qa

#23 MT-0008
  .github/workflows/test.yml
  Test
Labels: sprint1, env/qa

#38 MT-0027
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#43 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#44 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#45 Update Test
  Test
Labels: env/qa

#46 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#47 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#48 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa, auto-backport

#49 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa, auto-backport

#50 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1

#52 Sprints/sprint1
  .github/workflows/OnSprintLabedMergeToQA.yml
  Test
Labels: sprint1, auto-backport

#53 2
  .github/workflows/OnSprintLabedMergeToQA.yml
  Test
Labels: sprint1, env/qa, auto-backport, auto-backport-to-sprints/sprint1

#55 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1

#56 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1

#57 Test 1
  .backportrc.json
  Test
Labels: sprint1, env/qa

#58 Create TEST_1
  TEST_1
Labels: env/qa

#59 Update Test
  Test
Labels: sprint1, env/qa

#60 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#61 Update Test
  Test
Labels: env/qa

#62 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#63 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#64 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#65 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#66 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#67 Update OnSprintLabedMergeToQA.yml
  .github/workflows/OnSprintLabedMergeToQA.yml
Labels: sprint1, env/qa

#70 Mt 0035
  Test
Labels: sprint1, env/qa

#72 MT-0037
  TEST_1
Labels: env/qa

#77 MT-0040
  TEST_1
Labels: env/qa

#92 MT-0043
  Test
Labels: sprint1, env/qa
